#!/bin/bash
set -e

# Generated by lab-save on 2026-09-02T15:16:37Z
# Host: ABR-Host
# Edit freely. This is an ordinary shell startup script.
# vrf-mgmt / table 4094 is recreated automatically by the entrypoint.


vlan-create eth1 50



ip-set eth1.50 192.168.50.10/24

default-gw 192.168.50.1 eth1.50


