#!/bin/bash
set -e

# Generated by lab-save on 2026-09-07T14:27:55Z
# Host: host4
# Edit freely. This is an ordinary shell startup script.
# vrf-mgmt / table 4094 is recreated automatically by the entrypoint.


vlan-create eth1 100
vlan-create eth1 1111
vlan-create eth1 200



ip-set eth1.100 192.168.100.50/24
ip-set eth1.1111 192.168.111.50/24
ip-set eth1.200 192.168.200.50/24


dhcp-pool-create eth1.100 192.168.100.100 192.168.100.199 255.255.255.0 192.168.100.1 192.168.100.1 1h
dhcp-pool-create eth1.1111 192.168.111.100 192.168.111.199 255.255.255.0 192.168.111.1 192.168.111.1 1h
dhcp-pool-create eth1.200 192.168.200.100 192.168.200.199 255.255.255.0 192.168.200.1 192.168.200.1 1h
dhcp-server-start





