#!/bin/bash
set -e

# Generated by lab-save on 2026-09-02T15:16:37Z
# Host: host2
# Edit freely. This is an ordinary shell startup script.
# vrf-mgmt / table 4094 is recreated automatically by the entrypoint.





ip-set eth1 192.168.200.10/24

default-gw 192.168.200.1 eth1


