#!/bin/bash
set -e

# Generated by lab-save on 2026-09-02T20:23:42Z
# Host: host1
# Edit freely. This is an ordinary shell startup script.
# vrf-mgmt / table 4094 is recreated automatically by the entrypoint.












