#!/bin/bash
set -e

# Generated by lab-save on 2026-09-02T15:16:37Z
# Host: host3
# Edit freely. This is an ordinary shell startup script.
# vrf-mgmt / table 4094 is recreated automatically by the entrypoint.


vlan-create eth1 100
vlan-create eth1 200



ip-set eth1.100 192.168.100.200/24
ip-set eth1.200 192.168.200.10/24



