#!/bin/bash
set -e

# Generated by lab-save on 2026-09-07T14:27:54Z
# Host: host2
# Edit freely. This is an ordinary shell startup script.
# vrf-mgmt / table 4094 is recreated automatically by the entrypoint.









pc-phone-create eth1
pc-phone-create eth2
pc-phone-create eth3
pc-phone-create eth4
pc-phone-create eth5
pc-phone-create eth6
pc-phone-create eth7
pc-phone-create eth8



